# Site settings
title: CodeLovers
email: daniel@codelovers.at
description: "In this blog I’ll write about programming in general and web development with PHP, Symfony and JavaScript in special."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: h2online
github_username:  CodeLoversAt

# Build settings
markdown: kramdown
# highlighter: rouge
lsi:         false

kramdown:
    input: GFM
permalink: pretty

excerpt_separator: "\n\n"

sass:
    style: :compressed
    sass_dir: _sass
